### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by kdpan** [IsXudongZhang/Molormer#1]
Hello, thanks for your rep. and it is an amazing work. Can you tell me the number in the third column represent in the CSV file of the dataset.
您的工作非常好，请问您的数据集的名字叫什么？数据集中csv文件的第三列的数字代表什么？（因为学校没买数据库看不了原论文）

**Comment by IsXudongZhang** [comment]
The data we used in the paper is a public dataset publised in DeepDDI. The third column means the DDI label (about 86 classes).

**Comment by kdpan** [comment]
Thank you very much !!!
